image:
  repository: https://hub.docker.com/r/erlafont/octoprint
  tag: 1.8.6
  pullPolicy: IfNotPresent


#  - https://github.com/cimadure/charts/tree/master/charts/stable/octoprint
#  - https://github.com/elafontaine/octoprint-docker
#  - https://hub.docker.com/r/erlafont/octoprint

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  ENABLE_MJPG_STREAMER: "true"
  # -- sets the Mjpg stream imput parameters
  # Example "-y -n -r 640x480"
  MJPG_STREAMER_INPUT:
  MJPG_STREAMER_INPUT_2:
  MJPG_STREAMER_INPUT_3:
  # -- sets the camera dev parameters
  # Example "/dev/video0"
  CAMERA_DEV:
  CAMERA_DEV_2:
  CAMERA_DEV_3:

service:
  main:
    ports:
      main:
        port: 10021
        targetPort: 80

persistence:
  data:
    enabled: true
    mountPath: "/octoprint"
  varrun:
    enabled: true

portal:
  enabled: true
